name: Test pgvecutils

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install PostgreSQL 16 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg lsb-release
        echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y postgresql-16 postgresql-server-dev-16

    - name: Install pgvector extension
      run: |
        git clone https://github.com/pgvector/pgvector.git
        cd pgvector
        make
        sudo make install

    - name: Build and Install pgvecutils
      run: |
        make
        sudo make install

    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql
        sudo systemctl status postgresql

    - name: Setup pgvector and pgvecutils
      run: |
        sudo -u postgres psql -c "CREATE EXTENSION vector;"
        sudo -u postgres psql -c "CREATE EXTENSION pgvecutils;"
        sudo -u postgres psql -c "SELECT vector_rand(5);"
